In [21]:
import numpy as np
np.set_printoptions(precision=4, suppress=True) # Prettier printing

In [22]:
import ur_analytic_ik

In [23]:
from ur_analytic_ik import ur5e
# import ur_analytic_ik.ur5e # Not allowed

In [24]:
ur5e.forward_kinematics(0, 0, 0, 0, 0, 0)

array([[ 1.    ,  0.    ,  0.    , -0.8172],
       [ 0.    ,  0.    , -1.    , -0.2329],
       [ 0.    ,  1.    ,  0.    ,  0.0628],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [25]:
eef_pose = np.identity(4)
eef_pose[0, 3] = -0.2
eef_pose[1, 3] = -0.2
eef_pose[2, 3] = 0.3
ur5e.inverse_kinematics(eef_pose)

[array([[ 0.2946, -1.4225,  2.7697, -2.918 ,  1.5708,  1.2761]]),
 array([[ 0.2946,  0.9268, -2.7697,  0.2721,  1.5708,  1.2761]]),
 array([[ 0.2946, -1.1519,  2.2565,  0.4662, -1.5708, -1.8654]]),
 array([[ 0.2946,  0.9356, -2.2565,  2.8917, -1.5708, -1.8654]]),
 array([[-1.8654,  2.206 ,  2.2565,  0.2499,  1.5708, -2.8469]]),
 array([[-1.8654, -1.9897, -2.2565,  2.6754,  1.5708, -2.8469]]),
 array([[-1.8654,  2.2148,  2.7697,  2.8695, -1.5708,  0.2946]]),
 array([[-1.8654, -1.7191, -2.7697, -0.2236, -1.5708,  0.2946]])]

In [26]:
from ur_analytic_ik import ur3e
ur3e.inverse_kinematics(eef_pose)

[array([[ 0.3036, -1.3492,  2.3681, -2.5897,  1.5708,  1.2671]]),
 array([[ 0.3036,  0.6954, -2.3681,  0.1019,  1.5708,  1.2671]]),
 array([[ 0.3036, -0.8368,  1.4621,  0.9455, -1.5708, -1.8744]]),
 array([[ 0.3036,  0.5062, -1.4621,  2.5267, -1.5708, -1.8744]]),
 array([[-1.8744,  2.6354,  1.4621,  0.6149,  1.5708, -2.8379]]),
 array([[-1.8744, -2.3048, -1.4621,  2.1961,  1.5708, -2.8379]]),
 array([[-1.8744,  2.4462,  2.3681,  3.0397, -1.5708,  0.3036]]),
 array([[-1.8744, -1.7924, -2.3681, -0.5519, -1.5708,  0.3036]])]

In [27]:
ur3e.forward_kinematics(0, 0, 0, 0, 0, 0)

array([[ 1.    ,  0.    ,  0.    , -0.4567],
       [ 0.    ,  0.    , -1.    , -0.2232],
       [ 0.    ,  1.    ,  0.    ,  0.0665],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [28]:
tcp_transform = np.identity(4)
tcp_transform[2, 3] = 0.2
tcp_pose = ur3e.forward_kinematics_with_tcp(0, 0, 0, 0, 0, 0, tcp_transform)
tcp_pose

array([[ 1.    ,  0.    ,  0.    , -0.4567],
       [ 0.    ,  0.    , -1.    , -0.4232],
       [ 0.    ,  1.    ,  0.    ,  0.0665],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [29]:
ur3e.forward_kinematics(0, 0, 0, 0, 0, 0) @ tcp_transform

array([[ 1.    ,  0.    ,  0.    , -0.4567],
       [ 0.    ,  0.    , -1.    , -0.4232],
       [ 0.    ,  1.    ,  0.    ,  0.0665],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [30]:
ur3e.inverse_kinematics_with_tcp(np.array(tcp_pose), tcp_transform)

[array([[ 0.,  0.,  0., -0.,  0.,  0.]]),
 array([[-2.5828,  3.1416,  0.    , -3.1416, -2.5828, -0.    ]]),
 array([[-2.5828, -3.1416, -0.    ,  3.1416, -2.5828, -0.    ]])]

In [31]:
fk = ur3e.forward_kinematics
fk(0,0,0,0,0,0)

array([[ 1.    ,  0.    ,  0.    , -0.4567],
       [ 0.    ,  0.    , -1.    , -0.2232],
       [ 0.    ,  1.    ,  0.    ,  0.0665],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [32]:
ur3e.inverse_kinematics(np.array(fk(0,0,0,0,0,0)))

[array([[ 0.,  0.,  0., -0.,  0.,  0.]]),
 array([[-2.5828,  3.1416,  0.    , -3.1416, -2.5828, -0.    ]]),
 array([[-2.5828, -3.1416, -0.    ,  3.1416, -2.5828, -0.    ]])]

In [46]:
%%timeit
joint_config = (np.random.rand(6)*2-1)*np.pi


3.39 μs ± 107 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [50]:
%%timeit
joint_config = (np.random.rand(6)*2-1)*np.pi
fk = ur5e.forward_kinematics(*joint_config)

8.37 μs ± 80.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [62]:
# time the function for random poses
import time 
N=100000
total_time = 0
for i in range(N):
    joint_config = (np.random.rand(6)*2-1)*np.pi
    fk = ur5e.forward_kinematics(*joint_config)
    start = time.time()
    ik = ur5e.inverse_kinematics(fk)
    end = time.time()
    duration = end - start 
    total_time += duration

print(f"average time ={total_time/N*1e6} µs")
 

average time =18.585238456726074 µs


In [53]:
%%timeit
ur3e.inverse_kinematics_with_tcp(eef_pose, tcp_transform)

18.9 μs ± 209 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [36]:
ur3e.inverse_kinematics(eef_pose)

[array([[ 0.3036, -1.3492,  2.3681, -2.5897,  1.5708,  1.2671]]),
 array([[ 0.3036,  0.6954, -2.3681,  0.1019,  1.5708,  1.2671]]),
 array([[ 0.3036, -0.8368,  1.4621,  0.9455, -1.5708, -1.8744]]),
 array([[ 0.3036,  0.5062, -1.4621,  2.5267, -1.5708, -1.8744]]),
 array([[-1.8744,  2.6354,  1.4621,  0.6149,  1.5708, -2.8379]]),
 array([[-1.8744, -2.3048, -1.4621,  2.1961,  1.5708, -2.8379]]),
 array([[-1.8744,  2.4462,  2.3681,  3.0397, -1.5708,  0.3036]]),
 array([[-1.8744, -1.7924, -2.3681, -0.5519, -1.5708,  0.3036]])]

In [37]:
ur3e.inverse_kinematics_closest(eef_pose, *np.array([0, 0, 0, 0, 0, 0]))

[array([[ 0.3036, -1.3492,  2.3681, -2.5897,  1.5708,  1.2671]])]

In [38]:
for pose in ur3e.inverse_kinematics(eef_pose):
    print(np.linalg.norm(pose))

4.277890059743718
3.2042709484377037
3.131312140729875
3.8537087185528494
4.8472525160580435
5.129061108186763
5.186961358957139
3.8985061740861737


In [39]:
import numpy as np
from ur_analytic_ik import ur3e

joints = np.zeros(6)
eef_pose = np.identity(4)
eef_pose[2, 3] = 0.4
tcp_transform = np.identity(4)
tcp_transform[2, 3] = 0.1

ur3e.forward_kinematics(0, 0, 0, 0, 0, 0)
ur3e.forward_kinematics(*joints)
tcp_pose = ur3e.forward_kinematics_with_tcp(*joints, tcp_transform)

joint_solutions = ur3e.inverse_kinematics(eef_pose)
joint_solutions = ur3e.inverse_kinematics_closest(eef_pose, *joints)
joint_solutions = ur3e.inverse_kinematics_with_tcp(eef_pose, tcp_transform)

In [40]:
import numpy as np
from ur_analytic_ik import ur5e

eef_pose = np.identity(4)
X = np.array([-1.0, 0.0, 0.0])
Y = np.array([0.0, 1.0, 0.0])
Z = np.array([0.0, 0.0, -1.0])
top_down_orientation = np.column_stack([X, Y, Z])
translation = np.array([-0.2, -0.2, 0.2])

eef_pose[:3, :3] = top_down_orientation
eef_pose[:3, 3] = translation

solutions = ur5e.inverse_kinematics(eef_pose)